### PR TITLE
Remove completed bounties

### PR DESCRIPTION
**Pull request by benthecarman**

### CODE REVIEW

**Comment by nvk** [comment]
Are these completed or withdrawn?

**Comment by benthecarman** [comment]
Legends of Lightning is over: https://makers.bolt.fun/tournaments/1/overview

The wasabi Lightning Privacy was completed as well: https://twitter.com/futurepaul/status/1598026480717811713?s=20&t=7uR78fWd3j_bRhGcr_SGJw

**Comment by nvk** [comment]
Nvm, just saw the title. Reading this one the phone…

don’t delete, change the status to “claimed” this way the example lives on.

**Comment by benthecarman** [comment]
> don’t delete, change the status to “claimed” this way the example lives on.

Fixed

**Comment by nvk** [comment]
Merci!

**Pull request merged**
